package de.hswt.fi.ui.vaadin;

public class UIMessageKeys {

	public static final String DEFAULT_ERROR_MESSAGE = "DEFAULT_ERROR_MESSAGE";

	private UIMessageKeys() {
		// Prevent instantiation
	}

	// Cookie consent
	public static final String COOKIE_CONSENT_MESSAGE = "COOKIE_CONSENT_MESSAGE";

	public static final String COOKIE_CONSENT_BUTTON_CAPTION = "COOKIE_CONSENT_BUTTON_CAPTION";

	// Sidebar Items
	public static final String HOME_VIEW_CAPTION = "HOME_VIEW_CAPTION";

	public static final String INDEX_SEARCH_VIEW_CAPTION = "INDEX_SEARCH_VIEW_CAPTION";

	public static final String FILE_SEARCH_VIEW_CAPTION = "FILE_SEARCH_VIEW_CAPTION";

	public static final String QUICK_SEARCH_VIEW_CAPTION = "QUICK_SEARCH_VIEW_CAPTION";

	public static final String SEARCH_VIEW_CAPTION = "SEARCH_VIEW_CAPTION";

	public static final String SUSPECTED_TARGET_VIEW_CAPTION = "SUSPECTED_TARGET_VIEW_CAPTION";

	public static final String USER_ADMINSTRATION_VIEW_CAPTION = "USER_ADMINSTRATION_VIEW_CAPTION";

	public static final String PROCESSING_VIEW_CAPTION = "PROCESSING_VIEW_CAPTION";

	public static final String USER_NEED_LOG_IN_NOTIFICATION_CAPTION = "USER_NEED_LOG_IN_NOTIFICATION_CAPTION";

	public static final String USER_NEED_LOG_IN_NOTIFICATION_MESSAGE = "USER_NEED_LOG_IN_NOTIFICATION_MESSAGE";

	// Sections
	public static final String SECTIONS_TOP_CAPTION = "SECTIONS_TOP_CAPTION";

	public static final String SECTIONS_SEARCH_CAPTION = "SECTIONS_SEARCH_CAPTION";

	public static final String SECTIONS_PROCSSING_CAPTION = "SECTIONS_PROCSSING_CAPTION";

	public static final String SECTIONS_ADMINISTRATION_CAPTION = "SECTIONS_ADMINISTRATION_CAPTION";

	// Login UI
	public static final String LOGIN_UI_USER_NAME_TEXTFIELD_CAPTION = "LOGIN_UI_USER_NAME_TEXTFIELD_CAPTION";

	public static final String LOGIN_UI_PASSWORD_FIELD_CAPTION = "LOGIN_UI_PASSWORD_FIELD_CAPTION";

	public static final String LOGIN_UI_LOGIN_BUTTON_CAPTION = "LOGIN_UI_LOGIN_BUTTON_CAPTION";

	public static final String LOGIN_UI_REGISTER_LINK_CAPTION = "LOGIN_UI_REGISTER_LINK_CAPTION";

	public static final String LOGIN_UI_PASSWORD_LINK_CAPTION = "LOGIN_UI_PASSWORD_LINK_CAPTION";

	public static final String LOGIN_UI_LOGIN_ERROR_NOTIFICATION_CAPTION = "LOGIN_UI_LOGIN_ERROR_NOTIFICATION_CAPTION";

	public static final String LOGIN_UI_LOGIN_ERROR_NOTIFICATION_DESCRIPTION = "LOGIN_UI_LOGIN_ERROR_NOTIFICATION_DESCRIPTION";

	// Component Factory
	public static final String IONISATION_COMBO_BOX_CAPTION = "IONISATION_COMBO_BOX_CAPTION";

	public static final String STATIONARY_PHASE_COMBO_BOX_CAPTION = "STATIONARY_PHASE_COMBO_BOX_CAPTION";

	// Common Values shared around the Views
	public static final String SEARCH_BUTTON_CAPTION = "SEARCH_BUTTON_CAPTION";

	public static final String CLEAR_FIELDS_BUTTON_CAPTION = "CLEAR_FIELDS_BUTTON_CAPTION";

	public static final String CLEAR_SEARCH_BUTTON_CAPTION = "CLEAR_SEARCH_BUTTON_CAPTION";

	public static final String REPORT_SEARCH_BUTTON_CAPTION = "REPORT_SEARCH_BUTTON_CAPTION";

	public static final String DOWNLOAD_BUTTON_CAPTION = "DOWNLOAD_BUTTON_CAPTION";

	public static final String COLUMNS_CAPTION = "COLUMNS_CAPTION";

	public static final String REPORT_RECORDS_BUTTON_CAPTION = "REPORT_RECORDS_BUTTON_CAPTION";

	public static final String REPORT_RECORD_BUTTON_CAPTION = "REPORT_RECORD_BUTTON_CAPTION";

	public static final String CLEAR_SELECTION_BUTTON_CAPTION = "CLEAR_SELECTION_BUTTON_CAPTION";

	public static final String GRID_FILTER_INPUT_PROMPT = "GRID_FILTER_INPUT_PROMPT";

	public static final String CLEAR_FILTER_BUTTON_CAPTION = "CLEAR_FILTER_BUTTON_CAPTION";

	public static final String INVALID_SEARCH_NOTIFICATION_TITLE = "INVALID_SEARCH_NOTIFICATION_TITLE";

	public static final String INVALID_SEARCH_NOTIFICATION_DESCRIPTION = "INVALID_SEARCH_NOTIFICATION_DESCRIPTION";

	public static final String SELECT_CHECKBOX_CAPTION = "SELECT_CHECKBOX_CAPTION";

	public static final String RESULTS_COUNT_PARAMETERIZED = "RESULTS_COUNT_PARAMETERIZED";

	public static final String ERROR_NOTIFICATION_CAPTION = "ERROR_NOTIFICATION_CAPTION";

	// Abstract Layout View
	public static final String ABSTRACT_LAYOUT_VIEW_CHANGE_LAYOUT_CAPTION = "ABSTRACT_LAYOUT_VIEW_CHANGE_LAYOUT_CAPTION";

	// Index Search View
	public static final String INDEX_SEARCH_VIEW_VIEW_TITLE = "INDEX_SEARCH_VIEW_VIEW_TITLE";

	public static final String INDEX_SEARCH_VIEW_SEARCH_TITLE = "INDEX_SEARCH_VIEW_SEARCH_TITLE";

	// Search View
	public static final String SEARCH_VIEW_VIEW_TITLE = "SEARCH_VIEW_VIEW_TITLE";

	public static final String SEARCH_VIEW_SEARCH_TITLE = "SEARCH_VIEW_SEARCH_TITLE";

	public static final String SEARCH_VIEW_DETAILS_TITLE = "SEARCH_VIEW_DETAILS_TITLE";

	public static final String SEARCH_VIEW_RESULTS_TITLE = "SEARCH_VIEW_RESULTS_TITLE";

	public static final String SEARCH_VIEW_SEARCH_HISTORY_TITLE = "SEARCH_VIEW_SEARCH_HISTORY_TITLE";

	public static final String SEARCH_VIEW_SELECTION_HISTORY_TITLE = "SEARCH_VIEW_SELECTION_HISTORY_TITLE";

	public static final String SEARCH_VIEW_CATEGORY_GROUP_CAPTION = "SEARCH_VIEW_CATEGORY_GROUP_CAPTION";

	// Search Form Component
	public static final String SEARCH_FORM_COMPONENT_NAME_CAPTION = "SEARCH_FORM_COMPONENT_NAME_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_CAS_CAPTION = "SEARCH_FORM_COMPONENT_CAS_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_FORMULA_CAPTION = "SEARCH_FORM_COMPONENT_FORMULA_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_INCHI_KEY_CAPTION = "SEARCH_FORM_COMPONENT_INCHI_KEY_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_IUPAC_CAPTION = "SEARCH_FORM_COMPONENT_IUPAC_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_SMILES_CAPTION = "SEARCH_FORM_COMPONENT_SMILES_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_DATABASES_CAPTION = "SEARCH_FORM_COMPONENT_DATABASES_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_PUBLIC_ID_CAPTION = "SEARCH_FORM_COMPONENT_PUBLIC_ID_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_MASS_CAPTION = "SEARCH_FORM_COMPONENT_MASS_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_LOG_D_CAPTION = "SEARCH_FORM_COMPONENT_LOG_D_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_LOG_P_CAPTION = "SEARCH_FORM_COMPONENT_LOG_P_CAPTION";

	public static final String SEARCH_FORM_COMPONENT_TONNAGE_CAPTION = "SEARCH_FORM_COMPONENT_TONNAGE_CAPTION";

	// Search Handler
	public static final String SEARCH_HANDLER_ERROR_NO_DATASOURCE_SELECTED_CAPTION = "SEARCH_HANDLER_ERROR_NO_DATASOURCE_SELECTED_CAPTION";

	public static final String SEARCH_HANDLER_ERROR_NO_DATASOURCE_SELECTED_MESSAGE = "SEARCH_HANDLER_ERROR_NO_DATASOURCE_SELECTED_MESSAGE";

	// Quick Search View
	public static final String QUICK_SEARCH_VIEW_VIEW_TITLE = "QUICK_SEARCH_VIEW_VIEW_TITLE";

	public static final String QUICK_SEARCH_VIEW_SEARCH_TITLE = "QUICK_SEARCH_VIEW_SEARCH_TITLE";

	public static final String QUICK_SEARCH_VIEW_DETAILS_TITLE = "QUICK_SEARCH_VIEW_DETAILS_TITLE";

	public static final String QUICK_SEARCH_VIEW_RESULTS_TITLE = "QUICK_SEARCH_VIEW_RESULTS_TITLE";

	public static final String QUICK_SEARCH_VIEW_SEARCH_HISTORY_TITLE = "QUICK_SEARCH_VIEW_SEARCH_HISTORY_TITLE";

	public static final String QUICK_SEARCH_VIEW_SELECTION_HISTORY_TITLE = "QUICK_SEARCH_VIEW_SELECTION_HISTORY_TITLE";

	// Common values shared between QuickSearchForm and SearchForm
	public static final String SEARCH_FORM_MASS_TEXT_FIELD_CAPTION = "SEARCH_FORM_MASS_TEXT_FIELD_CAPTION";

	public static final String SEARCH_FORM_LOG_TEXT_FIELD_CAPTION = "SEARCH_FORM_LOG_TEXT_FIELD_CAPTION";

	public static final String SEARCH_FORM_HALOGEN_LAYOUT_CAPTION = "SEARCH_FORM_HALOGEN_LAYOUT_CAPTION";

	public static final String SEARCH_FORM_PPM_CAPTION = "SEARCH_FORM_PPM_CAPTION";

	public static final String SEARCH_FORM_INVALID_FIELD_INPUT_CAPTION = "SEARCH_FORM_INVALID_FIELD_INPUT_CAPTION";

	public static final String SEARCH_FORM_INVALID_FIELD_INPUT_MESSAGE = "SEARCH_FORM_INVALID_FIELD_INPUT_MESSAGE";

	public static final String SEARCH_FORM_CATEGORIES_WARNING = "SEARCH_FORM_CATEGORIES_WARNING";

	// User Administration View
	public static final String USER_USERNAME = "USER_USERNAME";

	public static final String USER_FIRSTNAME = "USER_FIRSTNAME";

	public static final String USER_LASTNAME = "USER_LASTNAME";

	public static final String USER_PASSWORD = "USER_PASSWORD";

	public static final String USER_PASSWORD_CONFIRMATION = "USER_PASSWORD_CONFIRMATION";

	public static final String USER_EMAIL = "USER_EMAIL";

	public static final String USER_ORGANISATION = "USER_ORGANISATION";

	public static final String USER_ENABLED = "USER_ENABLED";

	public static final String USER_VIEW_HEADER_LABEL = "USER_VIEW_HEADER_LABEL";

	public static final String USER_ADD_USER_BUTTON_CAPTION = "USER_ADD_USER_BUTTON_CAPTION";

	public static final String USER_DELETE_USER_BUTTON_CAPTION = "USER_DELETE_USER_BUTTON_CAPTION";

	public static final String USER_EDIT_USER_BUTTON_CAPTION = "USER_EDIT_USER_BUTTON_CAPTION";

	public static final String USER_CHANGE_PASSWORD_BUTTON_CAPTION = "USER_CHANGE_PASSWORD_BUTTON_CAPTION";

	public static final String ADMIN_UPLOAD_COMPOUND_DATA_BUTTON_CAPTION = "ADMIN_UPLOAD_COMPOUND_DATA_BUTTON_CAPTION";

	public static final String USER_ENABLED_CAPTION = "USER_ENABLED_CAPTION";

	public static final String USER_DISABLED_CAPTION = "USER_DISABLED_CAPTION";

	public static final String USER_ACTIVATIONMAIL = "USER_ACTIVATIONMAIL";

	public static final String USER_GROUP = "USER_GROUP";

	public static final String USER_VISIBLE = "USER_VISIBLE";

	public static final String USER_EMAIL_IS_INVALID = "USER_EMAIL_IS_INVALID";

	public static final String USER_EMAIL_IS_NOT_AVAILABLE = "USER_EMAIL_IS_NOT_AVAILABLE";

	public static final String ADMIN_REFRESH_TP_DATABASE_BUTTON = "ADMIN_REFRESH_TP_DATABASE_BUTTON";

	public static final String ADMIN_CONFIRM_REFRESH_TP_DATABASE_WINDOW_CAPTION = "ADMIN_CONFIRM_REFRESH_TP_DATABASE_WINDOW_CAPTION";

	public static final String ADMIN_CONFIRM_REFRESH_TP_DATABASE_WINDOW_DESCRIPTION = "ADMIN_CONFIRM_REFRESH_TP_DATABASE_WINDOW_DESCRIPTION";

	// File Search View
	public static final String FILE_SEARCH_VIEW_VIEW_TITLE = "FILE_SEARCH_VIEW_VIEW_TITLE";

	public static final String FILE_SEARCH_VIEW_SEARCH_TITLE = "FILE_SEARCH_VIEW_SEARCH_TITLE";

	public static final String FILE_SEARCH_VIEW_DETAILS_TITLE = "FILE_SEARCH_VIEW_DETAILS_TITLE";

	public static final String FILE_SEARCH_VIEW_RESULTS_TITLE = "FILE_SEARCH_VIEW_RESULTS_TITLE";

	public static final String FILE_SEARCH_VIEW_DATA_TITLE = "FILE_SEARCH_VIEW_DATA_TITLE";

	public static final String FILE_SEARCH_VIEW_SEARCH_HISTORY_TITLE = "FILE_SEARCH_VIEW_SEARCH_HISTORY_TITLE";

	public static final String FILE_SEARCH_VIEW_SELECTION_HISTORY_TITLE = "FILE_SEARCH_VIEW_SELECTION_HISTORY_TITLE";

	// Search Results Component
	public static final String SEARCH_RESULT_GRID_COLUMN_NAME = "SEARCH_RESULT_GRID_COLUMN_NAME";

	public static final String SEARCH_RESULT_GRID_COLUMN_CAS = "SEARCH_RESULT_GRID_COLUMN_CAS";

	public static final String SEARCH_RESULT_GRID_COLUMN_IUPAC = "SEARCH_RESULT_GRID_COLUMN_IUPAC";

	public static final String SEARCH_RESULT_GRID_COLUMN_SMILES = "SEARCH_RESULT_GRID_COLUMN_SMILES";

	public static final String SEARCH_RESULT_GRID_COLUMN_FORMULA = "SEARCH_RESULT_GRID_COLUMN_FORMULA";

	public static final String SEARCH_RESULT_GRID_COLUMN_TONNAGE = "SEARCH_RESULT_GRID_COLUMN_TONNAGE";

	public static final String SEARCH_RESULT_GRID_COLUMN_MASS = "SEARCH_RESULT_GRID_COLUMN_MASS";

	public static final String SEARCH_RESULT_GRID_COLUMN_HENRY_BOND = "SEARCH_RESULT_GRID_COLUMN_HENRY_BOND";

	public static final String SEARCH_RESULT_GRID_COLUMN_HENRY_GROUP = "SEARCH_RESULT_GRID_COLUMN_HENRY_GROUP";

	public static final String SEARCH_RESULT_GRID_COLUMN_HENRY_EXPER = "SEARCH_RESULT_GRID_COLUMN_HENRY_EXPER";

	public static final String SEARCH_RESULT_GRID_COLUMN_DATASOURCE = "SEARCH_RESULT_GRID_COLUMN_DATASOURCE";

	// Change Password Window
	public static final String CHANGE_PASSWORD_WINDOW_PASSWORD = "CHANGE_PASSWORD_WINDOW_PASSWORD";

	public static final String CHANGE_PASSWORD_WINDOW_GENERATE_PASSWORD = "CHANGE_PASSWORD_WINDOW_GENERATE_PASSWORD";

	// Windows
	public static final String ABSTRACT_WINDOW_OK_BUTTON_CAPTION = "ABSTRACT_WINDOW_OK_BUTTON_CAPTION";

	public static final String ABSTRACT_WINDOW_OK_BUTTON_DESCRIPTION = "ABSTRACT_WINDOW_OK_BUTTON_DESCRIPTION";

	public static final String ABSTRACT_WINDOW_CLOSE_BUTTON_CAPTION = "ABSTRACT_WINDOW_CLOSE_BUTTON_CAPTION";

	public static final String ABSTRACT_WINDOW_CLOSE_BUTTON_DESCRIPTION = "ABSTRACT_WINDOW_CLOSE_BUTTON_DESCRIPTION";

	public static final String WINDOW_REQUEST_USER_CAPTION = "WINDOW_REQUEST_USER_CAPTION";

	public static final String WINDOW_EDIT_USER_CAPTION = "WINDOW_EDIT_USER_CAPTION";

	public static final String WINDOW_ADMIN_EDIT_USER_CAPTION = "WINDOW_ADMIN_EDIT_USER_CAPTION";

	public static final String WINDOW_ADMIN_ADD_USER_CAPTION = "WINDOW_ADMIN_ADD_USER_CAPTION";

	public static final String WINDOW_CHANGE_PASSWORD_CAPTION = "WINDOW_CHANGE_PASSWORD_CAPTION";

	public static final String WINDOW_CONFIRMATION_CAPTION = "WINDOW_CONFIRMATION_CAPTION";

	public static final String WINDOW_UPLOAD_CAPTION = "WINDOW_UPLOAD_CAPTION";

	public static final String WINDOW_RAW_DATA_CAPTION = "WINDOW_RAW_DATA_CAPTION";

	public static final String WINDOW_BUG_REPORT_CAPTION = "WINDOW_BUG_REPORT_CAPTION";

	public static final String WINDOW_UPLOAD_COMPOUND_DATABASE_CAPTION = "WINDOW_UPLOAD_COMPOUND_DATABASE_CAPTION";

	// Contact Window
	public static final String CONTACT_WINDOW_WINDOW_CAPTION = "CONTACT_WINDOW_WINDOW_CAPTION";

	public static final String CONTACT_WINDOW_NAME_FIELD_CAPTION = "CONTACT_WINDOW_NAME_FIELD_CAPTION";

	public static final String CONTACT_WINDOW_MAIL_FIELD_CAPTION = "CONTACT_WINDOW_MAIL_FIELD_CAPTION";

	public static final String CONTACT_WINDOW_SUBJECT_FIELD_CAPTION = "CONTACT_WINDOW_SUBJECT_FIELD_CAPTION";

	public static final String CONTACT_WINDOW_MESSAGE_FIELD_CAPTION = "CONTACT_WINDOW_MESSAGE_FIELD_CAPTION";

	// Export Window
	public static final String EXPORT_WINDOW_WINDOW_CAPTION = "EXPORT_WINDOW_WINDOW_CAPTION";

	public static final String EXPORT_WINDOW_DOWNLOAD_BUTTON_CAPTION = "EXPORT_WINDOW_DOWNLOAD_BUTTON_CAPTION";

	public static final String EXPORT_WINDOW_DESELECT_ALL_BUTTON_CAPTION = "EXPORT_WINDOW_DESELECT_ALL_BUTTON_CAPTION";

	public static final String EXPORT_WINDOW_SELECT_ALL_BUTTON_CAPTION = "EXPORT_WINDOW_SELECT_ALL_BUTTON_CAPTION";

	public static final String EXPORT_WINDOW_OPTION_GROUP_CAPTION = "EXPORT_WINDOW_OPTION_GROUP_CAPTION";

	public static final String EXPORT_WINDOW_INCLUDE_SOURCES_CHECKBOX_CAPTION = "EXPORT_WINDOW_INCLUDE_SOURCES_CHECKBOX_CAPTION";

	public static final String EXPORT_WINDOW_FILE_TEXT_FIELD_CAPTION = "EXPORT_WINDOW_FILE_TEXT_FIELD_CAPTION";

	// Upload Compound Database Window
	public static final String UPLOAD_COMPOUND_WINDOW_DATABASE_LABEL_TEXT = "UPLOAD_COMPOUND_WINDOW_DATABASE_LABEL_TEXT";

	public static final String UPLOAD_COMPOUND_WINDOW_DATEFIELD_CAPTION = "UPLOAD_COMPOUND_WINDOW_DATEFIELD_CAPTION";

	// Confirm Upload Compound Database Window
	public static final String CONFIRM_UPLOAD_COMPOUND_WINDOW_CAPTION = "CONFIRM_UPLOAD_COMPOUND_WINDOW_CAPTION";

	public static final String CONFIRM_UPLOAD_COMPOUND_WINDOW_LABEL_TEXT = "CONFIRM_UPLOAD_COMPOUND_WINDOW_LABEL_TEXT";

	// Download Window
	public static final String DOWNLOAD_WINDOW_COLUMNS_CAPTION = "DOWNLOAD_WINDOW_COLUMNS_CAPTION";

	// User Menu Items
	public static final String USER_MENU_SETTINGS_CAPTION = "USER_MENU_SETTINGS_CAPTION";

	public static final String USER_MENU_PREFERENCES_CAPTION = "USER_MENU_PREFERENCES_CAPTION";

	public static final String USER_MENU_REGISTER_CAPTION = "USER_MENU_REGISTER_CAPTION";

	public static final String USER_MENU_LOGIN_CAPTION = "USER_MENU_LOGIN_CAPTION";

	public static final String USER_MENU_LOGOUT_CAPTION = "USER_MENU_LOGOUT_CAPTION";

	// Side Bar
	public static final String SIDE_BAR_COLLAPSE_BUTTON_DESCRIPTION = "SIDE_BAR_COLLAPSE_BUTTON_DESCRIPTION";

	public static final String SIDE_BAR_COLLAPSE_BUTTON_CAPTION = "SIDE_BAR_COLLAPSE_BUTTON_CAPTION";

	public static final String SIDE_BAR_LAST_UPDATE_CAPTION = "SIDE_BAR_LAST_UPDATE_CAPTION";

	// Report Window
	public static final String WINDOW_BUG_REPORT_DESCRIPION = "WINDOW_BUG_REPORT_DESCRIPION";

	public static final String WINDOW_BUG_REPORT_USERCOMMENT = "WINDOW_BUG_REPORT_USERCOMMENT";

	public static final String FROM = "FROM";

	public static final String WINDOW_BUG_REPORT_ANONYMOUS_CHECKBOX_CAPTION = "WINDOW_BUG_REPORT_ANONYMOUS_CHECKBOX_CAPTION";

	public static final String WINDOW_BUG_REPORT_ANONYMOUS_DESCRIPTION = "WINDOW_BUG_REPORT_ANONYMOUS_DESCRIPTION";

	public static final String SEND_REPORT_EMAIL_SUCCESS = "SEND_REPORT_EMAIL_SUCCESS";

	public static final String SEND_REPORT_EMAIL_ERROR = "SEND_REPORT_EMAIL_ERROR";

	public static final String REPORT_UTIL_SUBMITTED_DATA_TEXT = "REPORT_UTIL_SUBMITTED_DATA_TEXT";

	// Search History Tree
	public static final String SEARCH_HISTORY_TREE_ITEM_QUICKSEARCH = "SEARCH_HISTORY_TREE_ITEM_QUICKSEARCH";

	public static final String SEARCH_HISTORY_TREE_ITEM_SEARCH = "SEARCH_HISTORY_TREE_ITEM_SEARCH";

	public static final String SEARCH_HISTORY_TREE_ITEM_INDEXSEARCH = "SEARCH_HISTORY_TREE_ITEM_SEARCH";

	public static final String SEARCH_HISTORY_TREE_ITEM_PARAMETER = "SEARCH_HISTORY_TREE_ITEM_PARAMETER";

	public static final String SEARCH_HISTORY_TREE_ITEM_SELECTED_RESULTS = "SEARCH_HISTORY_TREE_ITEM_RESULTS";

	public static final String SEARCH_HISTORY_TREE_ITEM_UNDECLARED_ENTRY = "SEARCH_HISTORY_TREE_ITEM_UNDEFINED_ENTRY";

	public static final String SEARCH_HISTORY_TREE_INDEX_CHAR = "SEARCH_HISTORY_TREE_INDEX_CHAR";

	public static final String SEARCH_HISTORY_TREE_PH = "SEARCH_HISTORY_TREE_PH";

	public static final String SEARCH_HISTORY_TREE_LISTS = "SEARCH_HISTORY_TREE_LISTS";

	public static final String SEARCH_HISTORY_CONTEXT_MENU_REMOVE = "SEARCH_HISTORY_CONTEXT_MENU_REMOVE";

	// Request User Account Window
	public static final String REQUEST_USER_ACCOUNT_WINDOW_CAPTION = "REQUEST_USER_ACCOUNT_WINDOW_CAPTION";

	public static final String REQUEST_USER_ACCOUNT_SUCCESS_NOTIFICATION_HEADER = "REQUEST_USER_ACCOUNT_SUCCESS_NOTIFICATION_HEADER";

	public static final String REQUEST_USER_ACCOUNT_SUCCESS_NOTIFICATION_TEXT = "REQUEST_USER_ACCOUNT_SUCCESS_NOTIFICATION_TEXT";

	public static final String REQUEST_USER_ACCOUNT_ERROR_NOTIFICATION_TEXT = "REQUEST_USER_ACCOUNT_ERROR_NOTIFICATION_TEXT";

	public static final String REQUEST_USER_ACCOUNT_WINDOW_DESCRIPTION = "REQUEST_USER_ACCOUNT_WINDOW_DESCRIPTION";

	public static final String REQUEST_USER_ACCOUNT_ERROR_INVALID_EMAIL = "REQUEST_USER_ACCOUNT_ERROR_INVALID_EMAIL";

	public static final String REQUEST_USER_ACCOUNT_ERROR_EMAIL_IN_USE = "REQUEST_USER_ACCOUNT_ERROR_EMAIL_IN_USE";

	// Reset Password Handler
	public static final String RESET_PASSWORD_HANDLER_SUCCESS_NOTIFICATION_HEADER = "RESET_PASSWORD_HANDLER_SUCCESS_NOTIFICATION_HEADER";

	public static final String RESET_PASSWORD_HANDLER_SUCCESS_NOTIFICATION_TEXT = "RESET_PASSWORD_HANDLER_SUCCESS_NOTIFICATION_TEXT";

	public static final String RESET_PASSWORD_HANDLER_MAIL_HEADER = "RESET_PASSWORD_HANDLER_MAIL_HEADER";

	public static final String RESET_PASSWORD_HANDLER_MAIL_MESSAGE = "RESET_PASSWORD_HANDLER_MAIL_MESSAGE";

	// Abstract Details Component
	public static final String ABSTRACT_DETAILS_COMPONENT_CATEGORY = "ABSTRACT_DETAILS_COMPONENT_CATEGORY";

	public static final String ABSTRACT_DETAILS_COMPONENT_VALUE = "ABSTRACT_DETAILS_COMPONENT_VALUE";

	public static final String ABSTRACT_DETAILS_COMPONENT_LIST = "ABSTRACT_DETAILS_COMPONENT_LIST";

	public static final String ABSTRACT_DETAILS_COMPONENT_DESCRIPTION = "ABSTRACT_DETAILS_COMPONENT_DESCRIPTION";

	public static final String ABSTRACT_DETAILS_COMPONENT_NAME = "ABSTRACT_DETAILS_COMPONENT_NAME";

	public static final String ABSTRACT_DETAILS_COMPONENT_METADATA_CAPTION = "ABSTRACT_DETAILS_COMPONENT_METADATA_CAPTION";
	
	public static final String ABSTRACT_DETAILS_COMPONENT_WEB_SEARCH_BY_NAME = "ABSTRACT_DETAILS_COMPONENT_WEB_SEARCH_BY_NAME";
	
	public static final String ABSTRACT_DETAILS_COMPONENT_WEB_SEARCH_BY_CAS = "ABSTRACT_DETAILS_COMPONENT_WEB_SEARCH_BY_CAS";
	
	public static final String ABSTRACT_DETAILS_COMPONENT_WEB_SEARCH_BY_INCHI = "ABSTRACT_DETAILS_COMPONENT_WEB_SEARCH_BY_INCHI";

	public static final String ABSTRACT_DETAILS_ENTRY_NAME = "ABSTRACT_DETAILS_ENTRY_NAME";

	// FI Entry
	public static final String FI_ENTRY_STRUCTURE = "FI_ENTRY_STRUCTURE";

	public static final String FI_ENTRY_CAS = "FI_ENTRY_CAS";

	public static final String FI_ENTRY_EC_NUMBER = "FI_ENTRY_EC_NUMBER";

	public static final String FI_ENTRY_NAME = "FI_ENTRY_NAME";

	public static final String FI_ENTRY_SMILES = "FI_ENTRY_SMILES";

	public static final String FI_ENTRY_IUPAC = "FI_ENTRY_IUPAC";

	public static final String FI_ENTRY_FORMULA = "FI_ENTRY_FORMULA";

	public static final String FI_ENTRY_MASS = "FI_ENTRY_MASS";

	public static final String FI_ENTRY_TONNAGE = "FI_ENTRY_TONNAGE";

	public static final String FI_ENTRY_HENRY_BOND = "FI_ENTRY_HENRY_BOND";

	public static final String FI_ENTRY_HENRY_GROUP = "FI_ENTRY_HENRY_GROUP";

	public static final String FI_ENTRY_HENRY_EXPER = "FI_ENTRY_HENRY_EXPER";

	public static final String FI_ENTRY_LOG_P = "FI_ENTRY_LOG_P";

	public static final String FI_ENTRY_LOG_D = "FI_ENTRY_LOG_D";

	public static final String FI_ENTRY_ADDITIONAL_NAMES = "FI_ENTRY_ADDITIONAL_NAMES";

	public static final String FI_ENTRY_MASSBANK_IDS = "FI_ENTRY_MASSBANK_IDS";

	public static final String FI_ENTRY_CATEGROIES = "FI_ENTRY_CATEGROIES";

	public static final String FI_ENTRY_SOURCE_LISTS = "FI_ENTRY_SOURCE_LISTS";

	public static final String FI_ENTRY_PUBLIC_ID = "FI_ENTRY_PUBLIC_ID";

	public static final String FI_ENTRY_INCHI = "FI_ENTRY_INCHI";

	public static final String FI_ENTRY_INCHI_KEY = "FI_ENTRY_INCHI_KEY";

	public static final String FI_ENTRY_SOURCE = "FI_ENTRY_SOURCE";

	public static final String FI_ENTRY_PH = "FI_ENTRY_PH";

	public static final String FI_ENTRY_LAST_DATE = "FI_ENTRY_LAST_DATE";

	public static final String FI_ENTRY_ADDITIONAL = "FI_ENTRY_ADDITIONAL";

	public static final String FI_ENTRY_DESCRIPTION = "FI_ENTRY_DESCRIPTION";

	// Details Section
	public static final String STRUCTURE_DETAILS_CAPTION = "STRUCTURE_DETAILS_CAPTION";

	public static final String GENERAL_DETAILS_CAPTION = "GENERAL_DETAILS_CAPTION";

	public static final String HENRY_DETAILS_CAPTION = "HENRY_DETAILS_CAPTION";

	public static final String CATEGORIES_DETAILS_CAPTION = "CATEGORIES_DETAILS_CAPTION";

	public static final String LISTS_DETAILS_CAPTION = "LISTS_DETAILS_CAPTION";

	public static final String LOG_D_DETAILS_CAPTION = "LOG_D_DETAILS_CAPTION";

	public static final String LOG_P_DETAILS_CAPTION = "LOG_P_DETAILS_CAPTION";

	public static final String ADDITIONAL_NAME_DETAILS_CAPTION = "ADDITIONAL_NAME_DETAILS_CAPTION";

	public static final String MASSBANK_DETAILS_CAPTION = "MASSBANK_DETAILS_CAPTION";

	public static final String EXTERNAL_LINKS_DETAILS_CAPTION = "EXTERNAL_LINKS_DETAILS_CAPTION";

	// Change Password Handler
	public static final String CHANGE_PASSWORD_ERROR_NOTIFICATION_CAPTION = "CHANGE_PASSWORD_ERROR_NOTIFICATION_CAPTION";

	public static final String CHANGE_PASSWORD_ERROR_NOTIFICATION_DESCRIPTION = "CHANGE_PASSWORD_ERROR_NOTIFICATION_DESCRIPTION";

	public static final String CHANGE_PASSWORD_SUCCESS_NOTIFICATION_CAPTION = "CHANGE_PASSWORD_SUCCESS_NOTIFICATION_CAPTION";

	// Edit User Handler
	public static final String ADMIN_EDIT_USER_HANDLER_ACTIVATION_MAIL_TEXT = "ADMIN_EDIT_USER_HANDLER_ACTIVATION_MAIL_TEXT";

	public static final String ADMIN_EDIT_USER_HANDLER_SUCCESS_NOTIFCATION = "ADMIN_EDIT_USER_HANDLER_SUCCESS_NOTIFCATION";

	public static final String ADMIN_EDIT_USER_HANDLER_ERROR_NOTIFICATION = "ADMIN_EDIT_USER_HANDLER_ERROR_NOTIFICATION";

	// Delete User Handler
	public static final String DELETE_USER_ERROR_NOTIFICATION_CAPTION = "DELETE_USER_ERROR_NOTIFICATION_CAPTION";

	public static final String DELETE_USER_ERROR_NOTIFICATION_DESCRIPTION = "DELETE_USER_ERROR_NOTIFICATION_DESCRIPTION";

	public static final String DELETE_USER_SUCCESS_NOTIFICATION_CAPTION = "DELETE_USER_SUCCESS_NOTIFICATION_CAPTION";

	public static final String DELETE_USER_DIALOG_CAPTION = "DELETE_USER_DIALOG_CAPTION";

	public static final String DELETE_USER_DIALOG_DESCRIPTION = "DELETE_USER_DIALOG_DESCRIPTION";

	// File Search Results Component
	public static final String FILE_SEARCH_RESULTS_COMPONENT_COLUMN_TARGET_IDENTIFIER = "FILE_SEARCH_RESULTS_COMPONENT_COLUMN_TARGET_IDENTIFIER";

	public static final String FILE_SEARCH_COMPONENT_COLUMN_TARGET_RETENTION_TIME = "FILE_SEARCH_RESULTS_COMPONENT_COLUMN_TARGET_RETENTION_TIME";

	public static final String FILE_SEARCH_COMPONENT_COLUMN_SCORE = "FILE_SEARCH_RESULTS_COMPONENT_COLUMN_SCORE";

	public static final String FILE_SEARCH_COMPONENT_COLUMN_LOOK_AT = "FILE_SEARCH_COMPONENT_COLUMN_LOOK_AT";

	public static final String FILE_SEARCH_COMPONENT_COLUMN_TARGET_MASS = "FILE_SEARCH_RESULTS_COMPONENT_COLUMN_TARGET_MASS";

	public static final String FILE_SEARCH_COMPONENT_COLUMN_DELTA_MASS = "FILE_SEARCH_RESULTS_COMPONENT_COLUMN_DELTA_MASS";

	// Reset password Window
	public static final String RESET_PASSWORD_WINDOW_WINDOW_CAPTION = "RESET_PASSWORD_WINDOW_WINDOW_CAPTION";

	public static final String RESET_PASSWORD_WINDOW_DESCRIPTION_LABEL_CAPTION = "RESET_PASSWORD_WINDOW_DESCRIPTION_LABEL_CAPTION";

	// Details Section component
	public static final String DETAILS_SECTION_COMPONENT_SOURCE_CAPTION = "DETAILS_SECTION_COMPONENT_SOURCE_CAPTION";

	public static final String DETAILS_SECTION_COMPONENT_ADDITIONAL_CAPTION = "DETAILS_SECTION_COMPONENT_ADDITIONAL_CAPTION";

	public static final String DETAILS_SECTION_COMPONENT_LAST_UPDATE_CAPTION = "DETAILS_SECTION_COMPONENT_LAST_UPDATE_CAPTION";

	// File Search Form Component
	public static final String FILE_SEARCH_FORM_COMPONENT_UPLOAD_FIELD_CAPTION = "FILE_SEARCH_FORM_COMPONENT_UPLOAD_FIELD_CAPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_UPLOAD_BUTTON_CAPTION = "FILE_SEARCH_FORM_COMPONENT_UPLOAD_BUTTON_CAPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_PASTE_BUTTON_CAPTION = "FILE_SEARCH_FORM_COMPONENT_PASTE_BUTTON_CAPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_CAPTION = "FILE_SEARCH_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_CAPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_DESCRIPTION = "FILE_SEARCH_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_DESCRIPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_TOO_MANY_FEATURES_DESCRIPTION = "FILE_SEARCH_FORM_COMPONENT_TOO_MANY_FEATURES_DESCRIPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_INVALID_RTI_FILE_NOTIFICATION_DESCRIPTION = "FILE_SEARCH_FORM_COMPONENT_INVALID_RTI_FILE_NOTIFICATION_DESCRIPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_CAPTION = "FILE_SEARCH_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_CAPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_DESCRIPTION = "FILE_SEARCH_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_DESCRIPTION";

	public static final String FILE_SEARCH_FORM_COMPONENT_NOTIFICATION_NO_FILE_SELECTED = "FILE_SEARCH_FORM_COMPONENT_NOTIFICATION_NO_FILE_SELECTED";

	public static final String FILE_SEARCH_FORM_LOADING_FILE_DESCRIPTION = "FILE_SEARCH_FORM_LOADING_FILE_DESCRIPTION";

	public static final String FILE_SEARCH_FORM_FILE_ENTRIES_DESCRIPTION = "FILE_SEARCH_FORM_FILE_ENTRIES_DESCRIPTION";

	// SpreadSheetWindow
	public static final String SPREADSHEET_WINDOW_WINDOW_CAPTION = "SPREADSHEET_WINDOW_WINDOW_CAPTION";

	public static final String SPREADSHEET_WINDOW_LABEL_CAPTION = "SPREADSHEET_WINDOW_LABEL_CAPTION";

	public static final String SPREADSHEET_WINDOW_FILENAME_PREFIX = "SPREADSHEET_WINDOW_FILENAME_PREFIX";

	// Source List Component
	public static final String SOURCE_LIST_COMPONENT_TITLE = "SOURCE_LIST_COMPONENT_TITLE";

	// RTI / Suspected Target Screening
	public static final String RTI_VIEW_VIEW_TITLE = "RTI_VIEW_VIEW_TITLE";

	public static final String RTI_SEARCH_VIEW_RESULTS_TITLE = "RTI_SEARCH_VIEW_RESULTS_TITLE";

	public static final String RTI_SEARCH_VIEW_SEARCH_TITLE = "RTI_SEARCH_VIEW_SEARCH_TITLE";

	// RTI Result Form Component
	public static final String RTI_RESULT_COLUMN_PH = "RTI_RESULT_COLUMN_PH";

	public static final String RTI_RESULT_COLUMN_TARGET_RT = "RTI_RESULT_COLUMN_TARGET_RT";

	public static final String RTI_RESULT_COLUMN_LOOK_AT = "RTI_RESULT_COLUMN_LOOK_AT";

	public static final String RTI_RESULT_COLUMN_SCORE = "RTI_RESULT_COLUMN_SCORE";

	public static final String RTI_RESULT_COLUMN_RESULT_LOG_D = "RTI_RESULT_COLUMN_RESULT_LOG_D";

	public static final String RTI_RESULT_COLUMN_TARGET_LOG_D = "RTI_RESULT_COLUMN_TARGET_LOG_D";

	public static final String RTI_RESULT_COLUMN_DELTA_RTI_RESULT_LOG_D = "RTI_RESULT_COLUMN_DELTA_RTI_RESULT_LOG_D";

	public static final String RTI_RESULT_COLUMN_RTI_ADJUSTED_RTI_LOGD = "RTI_RESULT_COLUMN_RTI_ADJUSTED_RTI_LOGD";

	public static final String RTI_RESULT_COLUMN_RTI_DELTA_ADJUSTED_RTI_RESULT_LOGD = "RTI_RESULT_COLUMN_RTI_DELTA_ADJUSTED_RTI_RESULT_LOGD";

	// RTI Search Form Component
	public static final String RTI_SEARCH_FORM_COMPONENT_UPLOAD_BUTTON_CAPTION = "RTI_SEARCH_FORM_COMPONENT_UPLOAD_BUTTON_CAPTION";

	public static final String RTI_SEARCH_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_CAPTION = "RTI_SEARCH_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_CAPTION";

	public static final String RTI_SEARCH_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_DESCRIPTION = "RTI_SEARCH_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_DESCRIPTION";

	public static final String RTI_SEARCH_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_CAPTION = "RTI_SEARCH_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_CAPTION";

	public static final String RTI_SEARCH_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_DESCRIPTION = "RTI_SEARCH_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_DESCRIPTION";

	public static final String RTI_SEARCH_FORM_COMPONENT_UPLOAD_FIELD_CAPTION = "RTI_SEARCH_FORM_COMPONENT_UPLOAD_FIELD_CAPTION";

	public static final String RTI_SEARCH_FORM_LOADING_FILE_DESCRIPTION = "RTI_SEARCH_FORM_LOADING_FILE_DESCRIPTION";

	public static final String RTI_SEARCH_FORM_FILE_ENTRIES_DESCRIPTION = "RTI_SEARCH_FORM_FILE_ENTRIES_DESCRIPTION";

	// RTI Data Component
	public static final String RTI_DATA_COMPONENT_HEADER_CAPTION = "RTI_DATA_COMPONENT_HEADER_CAPTION";

	public static final String RTI_HELP_COMPONENT_HEADER_CAPTION = "RTI_HELP_COMPONENT_HEADER_CAPTION";

	public static final String RTI_DATA_TARGET_COLUMN_INDEX = "RTI_DATA_TARGET_COLUMN_INDEX";

	public static final String RTI_DATA_TARGET_COLUMN_TARGET = "RTI_DATA_TARGET_COLUMN_TARGET";

	public static final String RTI_DATA_TARGET_COLUMN_RTI = "RTI_DATA_TARGET_COLUMN_RTI";

	public static final String RTI_DATA_TARGET_COLUMN_RT = "RTI_DATA_TARGET_COLUMN_RT";

	public static final String RTI_DATA_TARGET_COLUMN_LOG_D = "RTI_DATA_TARGET_COLUMN_LOG_D";

	public static final String RTI_DATA_TARGET_COLUMN_ACCURATE_MASS = "RTI_DATA_TARGET_COLUMN_ACCURATE_MASS";

	public static final String RTI_DATA_TARGET_COLUMN_MASS_CALCULATED = "RTI_DATA_TARGET_COLUMN_MASS_CALCULATED";

	public static final String RTI_DATA_TARGET_COLUMN_ELEMENTAL = "RTI_DATA_TARGET_COLUMN_ELEMENTAL";

	public static final String RTI_DATA_TARGET_COLUMN_MEAN_RT = "RTI_DATA_TARGET_COLUMN_MEAN_RT";

	public static final String RTI_DATA_TARGET_COLUMN_FIRST_RT = "RTI_DATA_TARGET_COLUMN_FIRST_RT";

	public static final String RTI_DATA_TARGET_COLUMN_SECOND_RT = "RTI_DATA_TARGET_COLUMN_SECOND_RT";

	public static final String RTI_DATA_TARGET_COLUMN_THIRD_RT = "RTI_DATA_TARGET_COLUMN_THIRD_RT";

	public static final String RTI_DATA_CALIBRATION_COLUMN_SUBSTANCE_NAME = "RTI_DATA_CALIBRATION_COLUMN_SUBSTANCE_NAME";

	public static final String RTI_DATA_CALIBRATION_COLUMN_RTI = "RTI_DATA_CALIBRATION_COLUMN_RTI";

	public static final String RTI_DATA_CALIBRATION_COLUMN_SIGNAL = "RTI_DATA_CALIBRATION_COLUMN_SIGNAL";

	public static final String RTI_DATA_CALIBRATION_COLUMN_MEAN_RT = "RTI_DATA_CALIBRATION_COLUMN_MEAN_RT";

	public static final String RTI_DATA_CALIBRATION_COLUMN_FIRST_RT = "RTI_DATA_CALIBRATION_COLUMN_FIRST_RT";

	public static final String RTI_DATA_CALIBRATION_COLUMN_SECOND_RT = "RTI_DATA_CALIBRATION_COLUMN_SECOND_RT";

	public static final String RTI_DATA_CALIBRATION_COLUMN_THIRD_RT = "RTI_DATA_CALIBRATION_COLUMN_THIRD_RT";

	// Logout Handler
	public static final String LOGOUT_HANDLER_CONFIRMATION_DIALOG_CAPTION = "LOGOUT_HANDLER_CONFIRMATION_DIALOG_CAPTION";

	public static final String LOGOUT_HANDLER_CONFIRMATION_DIALOG_DESCRIPTION = "LOGOUT_HANDLER_CONFIRMATION_DIALOG_DESCRIPTION";

	// Results Download Handler
	public static final String RESULTS_DOWNLOAD_HANDLER_EXCEL_SPREADSHEET_DEFINITION_PARAMETER = "RESULTS_DOWNLOAD_HANDLER_EXCEL_SPREADSHEET_DEFINITION_PARAMETER";

	public static final String RESULTS_DOWNLOAD_HANDLER_EXCEL_SPREADSHEET_DEFINITION_RESULTS = "RESULTS_DOWNLOAD_HANDLER_EXCEL_SPREADSHEET_DEFINITION_RESULTS";
	
	public static final String RESULTS_DOWNLOAD_HANDLER_EXCEL_SPREADSHEET_DEFINITION_NON_RESULTS = "RESULTS_DOWNLOAD_HANDLER_EXCEL_SPREADSHEET_DEFINITION_NON_RESULTS";
			
	public static final String RESULTS_DOWNLOAD_HANDLER_EXCEL_SPREADSHEET_DEFINITION_SCORE_SETTINGS = "RESULTS_DOWNLOAD_HANDLER_EXCEL_SPREADSHEET_DEFINITION_SCORE_SETTINGS";
	
	// Abstract Results Component
	public static final String ABSTRACT_RESULTS_COMPONENT_NO_RESULTS_NOTIFICATION_CAPTION = "ABSTRACT_RESULTS_COMPONENT_NO_RESULTS_NOTIFICATION_CAPTION";

	public static final String ABSTRACT_RESULTS_COMPONENT_NO_RESULTS_NOTIFICATION_DESCRIPTION = "ABSTRACT_RESULTS_COMPONENT_NO_RESULTS_NOTIFICATION_DESCRIPTION";

	public static final String ABSTRACT_RESULTS_COMPONENT_FIXED_COLUMN_CAPTION = "ABSTRACT_RESULTS_COMPONENT_FIXED_COLUMN_CAPTION";

	public static final String OPEN_SUMMARY_WINDOW_BUTTON_DESCRIPTION = "OPEN_SUMMARY_WINDOW_BUTTON_DESCRIPTION";

	public static final String ABSTRACT_RESULTS_COMPONENT_DOWNLOAD_MENU_RESULTS = "ABSTRACT_RESULTS_COMPONENT_DOWNLOAD_MENU_RESULTS";
	
	public static final String ABSTRACT_RESULTS_COMPONENT_DOWNLOAD_MENU_NON_RESULTS = "ABSTRACT_RESULTS_COMPONENT_DOWNLOAD_MENU_NON_RESULTS";
	
	public static final String ABSTRACT_RESULTS_COMPONENT_DOWNLOAD_MENU_COMPLETE = "ABSTRACT_RESULTS_COMPONENT_DOWNLOAD_MENU_COMPLETE";
	
	// Processing
	public static final String PROCESSING_VIEW_VIEW_TITLE = "PROCESSING_VIEW_VIEW_TITLE";

	// Processing Form
	public static final String PROCESSING_VIEW_SEARCH_TITLE = "PROCESSING_VIEW_SEARCH_TITLE";

	public static final String PROCESSING_VIEW_SEARCH_HISTORY_TITLE = "PROCESSING_VIEW_SEARCH_HISTORY_TITLE";

	public static final String PROCESSING_FORM_PRECURSOR_PPM = "PROCESSING_FORM_PRECURSOR_PPM";

	public static final String PROCESSING_FORM_FRAGMENTS_PPM = "PROCESSING_FORM_FRAGMENTS_PPM";

	public static final String PROCESSING_FORM_SCORING = "PROCESSING_FORM_SCORING";

	public static final String PROCESSING_FORM_PARAMETERS_HEADER = "PROCESSING_FORM_PARAMETERS_HEADER";

	public static final String PROCESSING_FORM_UPLOAD_FILE_HEADER = "PROCESSING_FORM_UPLOAD_FILE_HEADER";

	public static final String PROCESSING_FORM_UPLOAD_FILE_ERROR_CAPTION = "PROCESSING_FORM_UPLOAD_FILE_ERROR_CAPTION";

	public static final String PROCESSING_FORM_UPLOAD_FILE_ERROR_FILE_SIZE_EXCEEDED = "PROCESSING_FORM_UPLOAD_FILE_ERROR_FILE_SIZE_EXCEEDED";

	public static final String PROCESSING_FORM_UPLOAD_FILE_ERROR_UPLOAD_FAILED = "PROCESSING_FORM_UPLOAD_FILE_ERROR_UPLOAD_FAILED";

	public static final String PROCESSING_FORM_UPLOAD_FILE_ERROR_FILE_EXISTS = "PROCESSING_FORM_UPLOAD_FILE_ERROR_FILE_EXISTS";

	public static final String PROCESSING_FORM_UPLOAD_FILE_ERROR_CALIBRATION_FILE_EXISTS = "PROCESSING_FORM_UPLOAD_FILE_ERROR_CALIBRATION_FILE_EXISTS";

	public static final String PROCESSING_FORM_SCORING_HEADER = "PROCESSING_FORM_SCORING_HEADER";

	public static final String PROCESSING_FORM_MASS_SCREENING_SCORE = "PROCESSING_FORM_MASS_SCREENING_SCORE";
	
	public static final String PROCESSING_FORM_RTI_SCREENING_SCORE = "PROCESSING_FORM_RTI_SCREENING_SCORE";

	public static final String PROCESSING_FORM_MSMS_SCORE_WEIGHT = "PROCESSING_FORM_MSMS_SCORE";

	public static final String PROCESSING_FORM_TP_SCORE = "PROCESSING_FORM_TP_SCORE";

	public static final String PROCESSING_FORM_CHEMSPIDER_SCORE_WEIGHT = "PROCESSING_FORM_CHEMSPIDER_SCORE";

	public static final String PROCESSING_FORM_MASSBANK_SIMPLE_SCORE_WEIGHT = "PROCESSING_FORM_MASSBANK_SIMPLE_SCORE";

	public static final String PROCESSING_FORM_DATA_AVAILABLE_DESCRIPTION = "PROCESSING_FORM_DATA_AVAILABLE_DESCRIPTION";

	public static final String PROCESSING_FORM_PROCESSING_ACTIVATED_DESCRIPTION = "PROCESSING_FORM_PROCESSING_ACTIVATED_DESCRIPTION";

	public static final String PROCESSING_FORM_ADD_FILE_BUTTON_CAPTION = "PROCESSING_FORM_ADD_FILE_BUTTON_CAPTION";

	public static final String PROCESSING_FORM_SCORE_SETTINGS_BUTTON_CAPTION = "PROCESSING_FORM_SCORE_SETTINGS_BUTTON_CAPTION";

	public static final String PROCESSING_FORM_START_SCREENING_BUTTON = "PROCESSING_FORM_START_SCREENING_BUTTON";

	// Processing Upload Window
	public static final String PROCESSING_FORM_UPLOAD_WINDOW_UPLOAD_FIELD_CAPTION = "PROCESSING_FORM_UPLOAD_WINDOW_UPLOAD_FIELD_CAPTION";

	public static final String PROCESSING_FORM_UPLOAD_WINDOW_UPLOAD_RTI_BUTTON_CAPTION= "PROCESSING_FORM_UPLOAD_WINDOW_UPLOAD_RTI_BUTTON_CAPTION";
	
	public static final String PROCESSING_FORM_COMPONENT_UPLOAD_BUTTON_CAPTION = "PROCESSING_FORM_COMPONENT_UPLOAD_BUTTON_CAPTION";

	public static final String PROCESSING_FORM_COMPONENT_RTI_CALIBRATION_UPLOAD_MESSAGE = "PROCESSING_FORM_COMPONENT_RTI_CALIBRATION_UPLOAD_MESSAGE";

	public static final String PROCESSING_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_CAPTION = "PROCESSING_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_CAPTION";

	public static final String PROCESSING_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_DESCRIPTION = "PROCESSING_FORM_COMPONENT_INVALID_FILE_NOTIFICATION_DESCRIPTION";

	public static final String PROCESSING_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_CAPTION = "PROCESSING_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_CAPTION";

	public static final String PROCESSING_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_DESCRIPTION = "PROCESSING_FORM_COMPONENT_DUPLICATE_FILE_NOTIFICATION_DESCRIPTION";

	public static final String PROCESSING_FORM_FILE_ENTRIES_DESCRIPTION = "PROCESSING_FORM_FILE_ENTRIES_DESCRIPTION";
	
	// Processing Results
	public static final String PROCESSING_RESULT_TOP_COLUMN_RESULTS = "PROCESSING_RESULT_TOP_COLUMN_RESULTS";

	public static final String PROCESSING_RESULT_TOP_COLUMN_SCORES = "PROCESSING_RESULT_TOP_COLUMN_SCORES";

	public static final String PROCESSING_RESULT_TOP_COLUMN_SUBSTANCE = "PROCESSING_RESULT_TOP_COLUMN_SUBSTANCE";

	public static final String PROCESSING_RESULT_COLUMN_DETAILS = "PROCESSING_RESULT_COLUMN_DETAILS";

	public static final String PROCESSING_RESULT_COLUMN_TARGET = "PROCESSING_RESULT_COLUMN_TARGET";

	public static final String PROCESSING_RESULT_COLUMN_TARGET_RT = "PROCESSING_RESULT_COLUMN_TARGET_RT";

	public static final String PROCESSING_RESULT_COLUMN_RESULT_NAME = "PROCESSING_RESULT_COLUMN_RESULT_NAME";

	public static final String PROCESSING_RESULT_COLUMN_LOOK_AT = "PROCESSING_RESULT_COLUMN_LOOK_AT";

	public static final String PROCESSING_RESULT_COLUMN_SCORE = "PROCESSING_RESULT_COLUMN_SCORE";

	public static final String PROCESSING_RESULT_COLUMN_MASS_SCREENING_SCORE = "PROCESSING_RESULT_COLUMN_MASS_SCREENING_SCORE";
	
	public static final String PROCESSING_RESULT_COLUMN_RTI_SCREENING_SCORE = "PROCESSING_RESULT_COLUMN_RTI_SCREENING_SCORE";

	public static final String PROCESSING_RESULT_COLUMN_MSMS_SCORE = "PROCESSING_RESULT_COLUMN_MSMS_SCORE";

	public static final String PROCESSING_RESULT_COLUMN_MASSBANK_SCORE = "PROCESSING_RESULT_COLUMN_MASSBANK_SCORE";

	public static final String PROCESSING_RESULT_SHOW_DETAILS_BUTTON_CAPTION = "PROCESSING_RESULT_SHOW_DETAILS_BUTTON_CAPTION";

	public static final String PROCESSING_RESULT_HIDE_DETAILS_BUTTON_CAPTION = "PROCESSING_RESULT_HIDE_DETAILS_BUTTON_CAPTION";

	public static final String PROCESSING_RESULT_COLUMN_HAS_PATHWAY = "PROCESSING_RESULT_COLUMN_HAS_PATHWAY";

	public static final String PROCESSING_RESULTS_HELP_COMPONENT_CAPTION = "PROCESSING_RESULTS_HELP_COMPONENT_CAPTION";

	public static final String PROCESSING_RESULTS_NO_MSMS_SCORE = "PROCESSING_RESULTS_NO_MSMS_SCORE";

	public static final String PROCESSING_RESULTS_NO_RTI_SCORE = "PROCESSING_RESULTS_NO_RTI_SCORE";

	// MS/MS Details
	public static final String MS_MS_DETAILS_FRAGMENTS_CAPTION = "MS_MS_DETAILS_FRAGMENTS_CAPTION";

	public static final String MS_MS_DETAILS_CURRENT_SELECTION_CAPTION = "MS_MS_DETAILS_CURRENT_SELECTION_CAPTION";

	// Task Window
	public static final String TASK_WINDOW_CAPTION = "TASK_WINDOW_CAPTION";

	public static final String TASK_WINDOW_WAITING_CAPTION = "TASK_WINDOW_WAITING_CAPTION";

	public static final String TASK_WINDOW_PROCESSING_CAPTION = "TASK_WINDOW_PROCESSING_CAPTION";

	public static final String TASK_WINDOW_FINISHED_CAPTION = "TASK_WINDOW_FINISHED_CAPTION";

	public static final String TASK_WINDOW_PROCESSING_MASS = "TASK_WINDOW_PROCESSING_MASS";
	
	public static final String TASK_WINDOW_PROCESSING_RTI = "TASK_WINDOW_PROCESSING_RTI";
	
	public static final String TASK_WINDOW_PROCESSING_MSMS = "TASK_WINDOW_PROCESSING_MSMS";
	
	public static final String TASK_WINDOW_PROCESSING_TP = "TASK_WINDOW_PROCESSING_TP";
	
	public static final String TASK_WINDOW_PROCESSING_CHEMSPIDER = "TASK_WINDOW_PROCESSING_CHEMSPIDER";
	
	public static final String TASK_WINDOW_PROCESSING_MASSBANK = "TASK_WINDOW_PROCESSING_MASSBANK";

	// Summary Window
	public static final String SUMMARY_WINDOW_CAPTION = "SUMMARY_WINDOW_CAPTION";

	// File Search Result Summary
	public static final String FILE_SEARCH_RESULT_SUMMARY_BEAN_COLUMN_FEATURES = "FILE_SEARCH_RESULT_SUMMARY_BEAN_COLUMN_FEATURES";

	public static final String FILE_SEARCH_RESULT_SUMMARY_BEAN_COLUMN_LOCATED_FEATURES = "FILE_SEARCH_RESULT_SUMMARY_BEAN_COLUMN_LOCATED_FEATURES";

	public static final String FILE_SEARCH_RESULT_SUMMARY_BEAN_COLUMN_CANDIDATES_FOUND = "FILE_SEARCH_RESULT_SUMMARY_BEAN_COLUMN_CANDIDATES_FOUND";

	public static final String FILE_SEARCH_RESULT_SUMMARY_BEAN_COLUMN_UNLOCATED_FEATURES = "FILE_SEARCH_RESULT_SUMMARY_BEAN_COLUMN_UNLOCATED_FEATURES";

	// ResultContainer Content Components
	public static final String PROCESSING_UNLOCATED_COMPONENT_TITLE = "PROCESSING_UNLOCATED_COMPONENT_TITLE";

	public static final String PROCESSING_TRANSFORMATION_COMPONENT_TITLE = "PROCESSING_TRANSFORMATION_COMPONENT_TITLE";

	public static final String PROCESSING_HOMOLOGOUS_COMPONENT_TITLE = "PROCESSING_HOMOLOGOUS_COMPONENT_TITLE";

	// MSMS Details Component
	public static final String MSMS_DETAILS_COMPONENT_CAPTION = "MSMS_DETAILS_COMPONENT_CAPTION";

	public static final String MSMS_DETAILS_COMPONENT_NO_DATA = "MSMS_DETAILS_COMPONENT_NO_DATA";

	public static final String MSMS_DETAILS_COMPONENT_INTENSITY = "MSMS_DETAILS_COMPONENT_INTENSITY";

	public static final String MSMS_DETAILS_COMPONENT_MZ = "MSMS_DETAILS_COMPONENT_MZ";

	public static final String MSMS_DETAILS_COMPONENT_SELECTED_FEATURE_LABEL = "MSMS_DETAILS_COMPONENT_SELECTED_FEATURE_LABEL";
	
	public static final String MSMS_DETAILS_COMPONENT_SELECTED_FEATURE_LABEL_NO_DATA = "MSMS_DETAILS_COMPONENT_SELECTED_FEATURE_LABEL_NO_DATA";
	
	// Scoring Details Component
	public static final String SCORING_DETAILS_COMPONENT_SCORES_SEARCH = "SCORING_DETAILS_COMPONENT_SCORES_SEARCH";
	
	public static final String SCORING_DETAILS_COMPONENT_SCORES_RTI= "SCORING_DETAILS_COMPONENT_SCORES_RTI";
	
	public static final String SCORING_DETAILS_COMPONENT_SCORES_MSMS= "SCORING_DETAILS_COMPONENT_SCORES_MSMS";
	
	public static final String SCORING_DETAILS_COMPONENT_SCORES_CHEMSPIDER = "SCORING_DETAILS_COMPONENT_SCORES_CHEMSPIDER";
	
	public static final String SCORING_DETAILS_COMPONENT_SCORES_MASSBANK = "SCORING_DETAILS_COMPONENT_SCORES_MASSBANK";
	
	public static final String SCORING_DETAILS_COMPONENT_SCORES_COMBINED = "SCORING_DETAILS_COMPONENT_SCORES_COMBINED";
	
	public static final String SCORING_DETAILS_COMPONENT_SCORES_DESCRIPTION = "SCORING_DETAILS_COMPONENT_SCORES_DESCRIPTION";

	public static final String SCORING_DETAILS_COMPONENT_PROCESS_ROW_CAPTION = "SCORING_DETAILS_COMPONENT_PROCESS_ROW_CAPTION";

	public static final String SCORING_DETAILS_COMPONENT_NO_SCORE_AVAILABLE = "SCORING_DETAILS_COMPONENT_NO_SCORE_AVAILABLE";

	// Score Window
	public static final String SCORE_WINDOW_CAPTION = "SCORE_WINDOW_CAPTION";
	
	public static final String SCORE_WINDOW_DESCRIPTION = "SCORE_WINDOW_DESCRIPTION";
	
	public static final String SCORE_WINDOW_COLUMN_PROCESS = "SCORE_WINDOW_COLUMN_PROCESS";
	
	public static final String SCORE_WINDOW_COLUMN_DATA_AVAILABLE = "SCORE_WINDOW_COLUMN_DATA_AVAILABLE";
	
	public static final String SCORE_WINDOW_COLUMN_ACTIVATED = "SCORE_WINDOW_COLUMN_ACTIVATED";
	
	public static final String SCORE_WINDOW_COLUMN_WEIGHT = "SCORE_WINDOW_COLUMN_WEIGHT";
	
	public static final String SCORE_WINDOW_SUM = "SCORE_WINDOW_SUM";

	// User Settings Window
	public static final String USER_SETTINGS_WINDOW_EMAIL_ALREADY_REGISTERED = "USER_SETTINGS_WINDOW_EMAIL_ALREADY_REGISTERED";

	public static final String USER_SETTINGS_WINDOW_EMAIL_INVALID = "USER_SETTINGS_WINDOW_EMAIL_INVALID";
}