<!DOCTYPE html>
<html lang="en">
<body>
<p>This is an autogenerated message.</p> 
<p>
	<a href=${report.mailTo} target"_top">Click here to reply</a>
</p>
<p><span>Report Date: ${report.date}</span></p>
<p><span>Submitted by (Username): ${report.username}</span></p>
<p><span>Organisation: ${report.organisation}</span></p>
<p><span>Contact E-Mail: ${report.email}</span></p>
<p><span>Reported Entries:</span></p>

<table style="border-collapse:collapse;">
  <tr>
    <th style="border: 1px solid black">Public ID</th>
    <th style="border: 1px solid black">Name</th>		
    <th style="border: 1px solid black">SMILES</th>
    <th style="border: 1px solid black">InChi</th>
    <th style="border: 1px solid black">InChi Key</th>
  </tr>

<#list report.entries as entry>
    <tr>
        <td style="border: 1px solid black" >${entry.publicID}</td>
        <td style="border: 1px solid black">${entry.name.value}</td>
        <td style="border: 1px solid black">${entry.smiles.value}</td>
        <td style="border: 1px solid black">${entry.inchi.value}</td>
        <td style="border: 1px solid black">${entry.inchiKey.value}</td>
    </tr>
</#list>

</table>

<p><span>Comment: ${report.comment}</span></p>	
</body>
</html>