<!DOCTYPE html>
<html lang="en">
<body>
<p>This is an autogenerated message.</p> 
<p>
	<a href=${report.mailTo} target"_top">Click here to reply</a>
</p>
<p><span>Report Date: ${report.date}</span></p>
<p><span>Submitted by (Username): ${report.username}</span></p>
<p><span>Organisation: ${report.organisation}</span></p>
<p><span>Contact E-Mail: ${report.email}</span></p>
<p><span>Selected Source lists:</span></p>
<ul>
<#list report.sourceLists as sourceList>
   <li>${sourceList.name}</li>
</#list>
</ul>
</table>
<p><span>Processing Job: </span></p>
<ul>

<#if report.searchParameter.settings.ph??>
    <li>PH: ${report.searchParameter.settings.ph}</li>
</#if>

<#if report.searchParameter.settings.ppm??>
<li>PPM: ${report.searchParameter.settings.ppm}</li>
</#if>

<#if report.searchParameter.settings.ionisation??>
<li>Ionisation: ${report.searchParameter.settings.ionisation}</li>
</#if>

</ul>

<p><span>Comment: ${report.comment}</span></p>	
</body>
</html>