<!DOCTYPE html>
<html lang="en">
<body>
<p>This is an autogenerated message.</p> 
<p>
	<a href=${report.mailTo} target"_top">Click here to reply</a>
</p>
<p><span>Report Date: ${report.date}</span></p>
<p><span>Submitted by (Username): ${report.username}</span></p>
<p><span>Organisation: ${report.organisation}</span></p>
<p><span>Contact E-Mail: ${report.email}</span></p>
<p><span>Selected Source lists:</span></p>
<ul>
<#list report.sourceLists as sourceList>
    <li>${sourceList.name}</li>
</#list>
</ul>
</table>
<p><span>Search Parameter: </span></p>
<ul>
<#if report.searchParameter.cas??>
<li>Cas: ${report.searchParameter.cas}</li>
</#if>

<#if report.searchParameter.name??>
<li>Name: ${report.searchParameter.name}</li>
</#if>

<#if report.searchParameter.elementalFormula??>
<li>Formula: ${report.searchParameter.elementalFormula}</li>
</#if>

<#if report.searchParameter.iupac??>
<li>IUPAC: ${report.searchParameter.iupac}</li>
</#if>

<#if report.searchParameter.smiles??>
<li>SMILES: ${report.searchParameter.smiles}</li>
</#if>

<#if report.searchParameter.smilesStandard??>
<li>SMILES Standard: ${report.searchParameter.smilesStandard}</li>
</#if>

<#if report.searchParameter.accurateMass ??>
<li>Accurate Mass: ${report.searchParameter.accurateMass}</li>
</#if>

<#if report.searchParameter.ppm != 0>
<li>PPM: ${report.searchParameter.ppm}</li>
</#if>

<#if report.searchParameter.ionisation??>
<li>Ionisation: ${report.searchParameter.ionisation}</li>
</#if>

<#if report.searchParameter.logD??>
<li>LogD: ${report.searchParameter.logD}</li>
</#if>


<#if !report.searchParameter.categories??>

#elseif(!report.searchParameter.categories.isEmpty())
<li>Selected categories:</li>
<ul>
    <#list report.report.searchParameter.categories as $category>
        <li>${sourceList.name}</li>
    </#list>
</ul>
</#if>

<#if report.searchParameter.indexChar == ' '>

<li>Index: ${report.searchParameter.indexChar}</li>
</#if>

<#if report.searchParameter.publicID??>
<li>STOFFIDENT-ID: ${report.searchParameter.publicID}</li>
</#if>

<#if report.searchParameter.inchiKey??>
<li>InChi Key: ${report.searchParameter.inchiKey}</li>
</#if>
</ul>

<p><span>Comment: ${report.comment}</span></p>	
</body>
</html>