= FOR-IDENT
:toc: left
:toclevels: 3
:sectnums:
:sectnumlevels: 3

== Overview
This documents contains a getting started guide and overview for the FOR-IDENT platform, the
successor of the ground breaking database STOFF-IDENT.

=== Technologies
Currently FOR-IDENT is build upon the following technologies:

* Java 8
* Spring 4
* Spring Boot
* Vaadin 7
* Gradle
* Git
* JPA (EclipseLink)
* Asciidoctor


=== Server

==== Kontakt
https://servicedesk.lrz.de/

==== Details:
Bestellt von: Tobias Placht (LRZ Kennung: di73ten2)
VM-Name (max. 7 Zeichen): RIP
OS: Debian 8
Anzahl vCPU (1-8): 8
RAM (1-32 GB): 16 GB
Größe Systemfestplatte (ab 10 GB): 30GB
(optional)weitere Festplatten: Größe und Mountpunkt / Ordnername): 70 GB /srv/data
Benötigte Erreichbarkeit der VM (MWN oder weltweit): Weltweit
IP-Adresse(n) / Subnetze, die SSH-Zugriff erhalten sollen (notwendig!): Subnetz 10.154.4

===== User
Siehe: https://it-wiki.hswt.de/wiki/PW-BT#forident

==== Installlation Details

====== Java 8
Link: http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update
apt-get install oracle-java8-installer

===== Postgresql:
Link: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-9-4-on-debian-8

apt install postgresql-9.4 postgresql-client-9.4

Als "postgres" user verbinden
su - postgres
psql

Neuen Benutzer hinzufügen (als Benutzer postgres)
createuser --interactive

Datenbank hinzufügen
createdb fi-production

==== Open Port for PSQL
Add line in iptables
iptables -A INPUT -p tcp -s 10.154.4.0/255.255.255.0 -d 138.246.224.112 --dport 5432 -m tcp -j ACCEPT

Accept connection in PSQL
/etc/postgresql/9.4/main/postgresql.conf
....
listen_addresses = '*'
....

Accept connection type
/etc/postgresql/9.4/main/pg_hba.conf
....
host    all             all             0.0.0.0/0               md5
....

==== Native Libraries
jnati (0.8) / jniinchi

.jnati/repo/jniinchi/1.03_1/LINUX_AMD64/libJniInchi-1.03_1-LINUX-AMD64.so
.jnati/repo/jniinchi/1.03_1/LINUX_AMD64/MANIFEST.xml

===== Nginx
Link: https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-debian-8

apt install nginx

===== FI starten
java -javaagent:spring-instrument-4.2.4.RELEASE.jar
-jar de.hswt.fi.application-XXX.jar
--spring.profiles.active=production
--server.port=8080 > /dev/null 2>&1 &